version: '3'

services:
  db:
    image: mongo
    environment:
      - AUTH=yes
      - MONGODB_ADMIN_USER=${MONGO_DB_USER}
      - MONGODB_ADMIN_PASS=${MONGO_DB_PASSWORD}
      - MONGODB_APPLICATION_DATABASE=${MONGO_DB_NAME}
      - MONGO_DB_HOST = ${MONGO_DB_HOST}
      - MONGO_DB_PORT = ${MONGO_DB_PORT}
      - MONGO_DB_AUTH_MECHANISM = ${MONGO_DB_AUTH_MECHANISM}
    ports:
      - "27017:27017"
    volumes:
      - .:/app
  noti-docker:
    image: thinhnx75/noti-docker
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "7777:7777"
