apiVersion: apps/v1
kind: Deployment
metadata:
  name: noti-deployment
  namespace: hcm-oc
  labels:
    app: noti-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: noti-deployment
  template:
    metadata:
      labels:
        app: noti-deployment
    spec:
      containers:
        - name: noti-deployment
          image: thinhnx75/noti-docker:latest
          ports:
            - containerPort: 7777
          envFrom:
            - configMapRef:
                name: data-env
---
apiVersion: v1
kind: Service
metadata:
  name: noti-service
  namespace: hcm-oc
spec:
  selector:
    app: noti-deployment
  ports:
    - protocol: TCP
      port: 7777
      targetPort: 7777
